name: Generate Android Signed Apk

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Generate Apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Make Gradle file executable
      run: chmod +x gradlew
    - name: Assemble 'release' with Gradle
      run: ./gradlew assembleRelease
    - name: Sign Apk
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
        alias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}  
    - run: echo "Build status report=${{ job.status }}."
    - name: Upload App Bundle
      uses: actions/upload-artifact@v1
      with:
        name: demo-jetpack-compose-android-app
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}